### ISSUE TITLE
ToDo 

### ISSUE THREAD

**Issue by forkbabu** [Julia-Kolkata-User-Group/ExploreML-Julia#1]
- [ ] Tutorial on how to plot on Julia like Matplotlib
- [ ] Linear Algebra . Span,Trace,Rank of a matrix, Inverse, Det, Pseudoinv, Jacobian and Hessian
- [ ] Automatic Differentiation. Computing jvp and vjp of a neural network

**Comment by forkbabu** [comment]
cc: @ucalyptus @DSantra92

**Comment by forkbabu** [comment]
- [ ] Logistic Regression
- [ ] Support Vector Machines with KKT conditions
- [ ] K Nearest Neighbors

**Comment by ucalyptus** [comment]
https://medium.com/@kimfung/deploying-julia-projects-on-heroku-com-eb8da5248134
https://elements.heroku.com/buildpacks/optomatica/heroku-buildpack-julia

**Comment by Dsantra92** [comment]
I am done with the first notebook.

**Comment by ucalyptus** [comment]
@Dsantra92 make a PR here

**Comment by Dsantra92** [comment]
We can add a meta-programming notebook too

**Comment by ucalyptus** [comment]
> We can add a meta-programming notebook too

any examples ?
